# Create this file as render.yaml in your project root
services:
  - type: web
    name: whatsapp-campaign-manager
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://dizihub.onrender.com
    scaling:
      minInstances: 1
      maxInstances: 1