services:
  - type: web
    name: whatsapp-backend
    env: node
    buildCommand: npm install
    startCommand: node server/index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
